[pytest]
addopts = -s -v
markers =
    gateway: Mark for gateway service tests.
    operations: Mark for operations service tests.
    regression: Mark for regression tests.

;явно задаём pythonpath, добавляя корень проекта и каталог protos/gen. Это необходимо для корректной работы
;импортов protobuf-контрактов при локальном запуске тестов и обеспечивает одинаковое поведение на macOS, Windows и в CI.
pythonpath =
    .
    protos/gen
